/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.clienti.swing;

import com.mycompany.clienti.swing.entity.Cliente;

/**
 *
 * @author tss
 */
public class GesClienteFrame extends javax.swing.JFrame {

    private Cliente cliente = new Cliente();

    /**
     * Creates new form AddCliente
     */
    public GesClienteFrame() {
        initComponents();

    }

    public GesClienteFrame(Cliente selected) {
        initComponents();
        this.cliente = selected;
        jTFieldRagSoc.setText(cliente.getRagioneSociale());
        jTFieldIndirizzo.setText(cliente.getIndirizzo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExp = new javax.swing.JLabel();
        jLabelRagSoc = new javax.swing.JLabel();
        jLabelInd = new javax.swing.JLabel();
        jTFieldRagSoc = new javax.swing.JTextField();
        jTFieldIndirizzo = new javax.swing.JTextField();
        jButtonCommit = new javax.swing.JButton();
        jButtonCloseCurrent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelExp.setText("Aggiungi un nuovo CLIENTE");

        jLabelRagSoc.setText("Ragione SOCIALE:");

        jLabelInd.setText("Indirizzo/Sede:");

        jTFieldRagSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFieldRagSocActionPerformed(evt);
            }
        });

        jTFieldIndirizzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFieldIndirizzoActionPerformed(evt);
            }
        });

        jButtonCommit.setText("Invia");
        jButtonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommitActionPerformed(evt);
            }
        });

        jButtonCloseCurrent.setText("Esci");
        jButtonCloseCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseCurrentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelExp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonCloseCurrent)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRagSoc)
                                .addComponent(jLabelInd))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonCommit)
                                .addComponent(jTFieldRagSoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(jTFieldIndirizzo, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRagSoc)
                    .addComponent(jTFieldRagSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInd)
                    .addComponent(jTFieldIndirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCommit)
                .addGap(18, 18, 18)
                .addComponent(jButtonCloseCurrent)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFieldRagSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFieldRagSocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFieldRagSocActionPerformed

    private void jButtonCloseCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseCurrentActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseCurrentActionPerformed

    private void jButtonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommitActionPerformed
        // TODO add your handling code here:
        if (jTFieldRagSoc.getText().equals("")&&jTFieldIndirizzo.getText().equals("")) {
            Cliente cli = new Cliente();
            cli.setRagioneSociale(jTFieldRagSoc.getText());
            cli.setIndirizzo(jTFieldIndirizzo.getText());
            MainFrame.getEm().getTransaction().begin();
            MainFrame.getEm().persist(cli);
            MainFrame.getEm().getTransaction().commit();
        } else {
            cliente.setRagioneSociale(jTFieldRagSoc.getText());
            cliente.setIndirizzo(jTFieldIndirizzo.getText());
            MainFrame.getEm().getTransaction().begin();
            MainFrame.getEm().persist(cliente);
            MainFrame.getEm().getTransaction().commit();
        }
        jTFieldRagSoc.setText("");
        jTFieldIndirizzo.setText("");
    }//GEN-LAST:event_jButtonCommitActionPerformed

    private void jTFieldIndirizzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFieldIndirizzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFieldIndirizzoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GesClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GesClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GesClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GesClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GesClienteFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseCurrent;
    private javax.swing.JButton jButtonCommit;
    private javax.swing.JLabel jLabelExp;
    private javax.swing.JLabel jLabelInd;
    private javax.swing.JLabel jLabelRagSoc;
    private javax.swing.JTextField jTFieldIndirizzo;
    private javax.swing.JTextField jTFieldRagSoc;
    // End of variables declaration//GEN-END:variables
}
