/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.clienti.swing;

import com.mycompany.clienti.swing.entity.Cliente;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author tss
 */
public class MainFrame extends javax.swing.JFrame {

    private static EntityManager em;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initDB();
        loadClienti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableClienti = new javax.swing.JTable();
        JButtonAdd = new javax.swing.JButton();
        jButtonElimina = new javax.swing.JButton();
        JButtonEdit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuFile = new javax.swing.JMenu();
        JMenuFileEsci = new javax.swing.JMenuItem();
        jMenuFileRefresh = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableClienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Ragione Sociale", "Indirizzo"
            }
        ));
        JTableClienti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableClientiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableClienti);

        JButtonAdd.setText("Aggiungi Cliente");
        JButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddActionPerformed(evt);
            }
        });

        jButtonElimina.setText("Elimina");
        jButtonElimina.setEnabled(false);
        jButtonElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaActionPerformed(evt);
            }
        });

        JButtonEdit.setText("Modifica");
        JButtonEdit.setEnabled(false);
        JButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditActionPerformed(evt);
            }
        });

        JMenuFile.setText("File");

        JMenuFileEsci.setText("Esci");
        JMenuFileEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuFileEsciActionPerformed(evt);
            }
        });
        JMenuFile.add(JMenuFileEsci);

        jMenuFileRefresh.setText("Refresh");
        jMenuFileRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileRefreshActionPerformed(evt);
            }
        });
        JMenuFile.add(jMenuFileRefresh);

        jMenuBar1.add(JMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonElimina))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAdd)
                    .addComponent(jButtonElimina)
                    .addComponent(JButtonEdit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuFileEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuFileEsciActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JMenuFileEsciActionPerformed

    private void JButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddActionPerformed
        // TODO add your handling code here:
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pu");
//        EntityManager em = emf.createEntityManager();

        GesClienteFrame cliente = new GesClienteFrame();
        cliente.setVisible(true);
    }//GEN-LAST:event_JButtonAddActionPerformed

    private void jMenuFileRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileRefreshActionPerformed
        // TODO add your handling code here:
        loadClienti();
    }//GEN-LAST:event_jMenuFileRefreshActionPerformed

    private void jButtonEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaActionPerformed
        // TODO add your handling code here:
        JTableClienti.getSelectedRow();
        Object index = JTableClienti.getValueAt(JTableClienti.getSelectedRow(), 0);
        String sql = "select c from Cliente c where c.id=" + index;
        Cliente del = em.createQuery(sql, Cliente.class).getSingleResult();
        em.getTransaction().begin();
        em.remove(del);
        em.getTransaction().commit();
        loadClienti();
        JButtonEdit.setEnabled(false);
        jButtonElimina.setEnabled(false);
    }//GEN-LAST:event_jButtonEliminaActionPerformed

    private void JTableClientiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableClientiMouseClicked
        // TODO add your handling code here:
        JButtonEdit.setEnabled(true);
        jButtonElimina.setEnabled(true);
    }//GEN-LAST:event_JTableClientiMouseClicked

    private void JButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditActionPerformed
        // TODO add your handling code here:
        GesClienteFrame cliente = new GesClienteFrame(getSelected());
        //GesClienteFrame afc = new GesClienteFrame();
        cliente.setVisible(true);

        JButtonEdit.setEnabled(false);
        jButtonElimina.setEnabled(false);
    }//GEN-LAST:event_JButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAdd;
    private javax.swing.JButton JButtonEdit;
    private javax.swing.JMenu JMenuFile;
    private javax.swing.JMenuItem JMenuFileEsci;
    private javax.swing.JTable JTableClienti;
    private javax.swing.JButton jButtonElimina;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFileRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initDB() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pu");
        em = emf.createEntityManager();
    }

    public static EntityManager getEm() {
        return em;
    }

    private void loadClienti() {
        JTableClienti.setModel(new ClienteTableModel());
    }

    private Cliente getSelected() {
        Object index = JTableClienti.getValueAt(JTableClienti.getSelectedRow(), 0);
        String sql = "select c from Cliente c where c.id=" + index;
        Cliente edit = em.createQuery(sql, Cliente.class).getSingleResult();
        return edit;

    }
}